AllCops:
  DefaultFormatter: clang
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Metrics/BlockLength:
  Exclude:
  - kitchen-terraform.gemspec
  - Guardfile
  - spec/**/*
Metrics/ParameterLists:
  Exclude:
  - lib/terraform/group.rb
  - lib/terraform/plan_command.rb
Style/AccessorMethodName:
  Exclude:
  - lib/terraform/command_factory.rb
